FROM python:3.9-slim

RUN apt-get update && apt-get install -y build-essential git
RUN pip install --upgrade pip && pip install pipenv

WORKDIR /usr/src/app

ENTRYPOINT [ "/bin/sh", "-c" ]
CMD ["bash"]
