FROM node:lts-alpine as builder

WORKDIR /app
COPY frontend /app
RUN npm install
RUN npm run build

FROM nginx:latest
RUN rm -rf /etc/nginx/sites-enabled/default.conf
COPY nginx /etc/nginx/sites-enabled

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
EXPOSE 443
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]