apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: launch-katib-experiment-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2024-02-29T11:24:38.433130',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "An example to launch Katib
      Experiment with custom logic", "name": "Launch Katib Experiment"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: launch-katib-experiment
  templates:
  - name: best-hp
    container:
      args: ['echo Best HyperParameters: {{inputs.parameters.katib-launch-experiment-Best-Parameter-Set}}']
      command: [sh, -c]
      image: library/bash:4.4.23
    inputs:
      parameters:
      - {name: katib-launch-experiment-Best-Parameter-Set}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: katib-launch-experiment
    container:
      args:
      - --experiment-name
      - katib-example-{{ workflow.uid }}
      - --experiment-namespace
      - '{{ workflow.namespace }}'
      - --experiment-spec
      - '{"algorithm": {"algorithmName": "grid"}, "maxFailedTrialCount": 3, "maxTrialCount":
        3, "objective": {"goal": 50, "objectiveMetricName": "result", "type": "maximize"},
        "parallelTrialCount": 2, "parameters": [{"feasibleSpace": {"max": "50", "min":
        "0"}, "name": "x", "parameterType": "int"}, {"feasibleSpace": {"max": "50",
        "min": "0"}, "name": "y", "parameterType": "int"}], "trialTemplate": {"primaryContainerName":
        "real-my-container", "retain": true, "trialParameters": [{"description": "argument
        1", "name": "X", "reference": "x"}, {"description": "argument 2", "name":
        "Y", "reference": "y"}], "trialSpec": {"apiVersion": "batch/v1", "kind": "Job",
        "spec": {"template": {"metadata": {"annotations": {"sidecar.istio.io/inject":
        "false"}}, "spec": {"containers": [{"args": ["custom.py", "--x", "${trialParameters.X}",
        "--y", "${trialParameters.Y}"], "command": ["python"], "image": "129231402580.dkr.ecr.ap-northeast-1.amazonaws.com/base_image:katib-test",
        "name": "real-my-container"}], "restartPolicy": "Never"}}}}}}'
      - --experiment-timeout-minutes
      - '60'
      - --delete-after-done
      - "False"
      - --output-file
      - /tmp/outputs/Best_Parameter_Set/data
      command: [python, src/launch_experiment.py]
      image: docker.io/kubeflowkatib/kubeflow-pipelines-launcher
    outputs:
      parameters:
      - name: katib-launch-experiment-Best-Parameter-Set
        valueFrom: {path: /tmp/outputs/Best_Parameter_Set/data}
      artifacts:
      - {name: katib-launch-experiment-Best-Parameter-Set, path: /tmp/outputs/Best_Parameter_Set/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Katib
          Experiment launcher", "implementation": {"container": {"args": ["--experiment-name",
          {"inputValue": "Experiment Name"}, "--experiment-namespace", {"inputValue":
          "Experiment Namespace"}, "--experiment-spec", {"inputValue": "Experiment
          Spec"}, "--experiment-timeout-minutes", {"inputValue": "Experiment Timeout
          Minutes"}, "--delete-after-done", {"inputValue": "Delete Finished Experiment"},
          "--output-file", {"outputPath": "Best Parameter Set"}], "command": ["python",
          "src/launch_experiment.py"], "image": "docker.io/kubeflowkatib/kubeflow-pipelines-launcher"}},
          "inputs": [{"default": "", "description": "Experiment name", "name": "Experiment
          Name", "type": "String"}, {"default": "anonymous", "description": "Experiment
          namespace", "name": "Experiment Namespace", "type": "String"}, {"default":
          "{}", "description": "Experiment specification in dict format", "name":
          "Experiment Spec", "type": "JsonObject"}, {"default": 1440, "description":
          "Time in minutes to wait for the Experiment to complete", "name": "Experiment
          Timeout Minutes", "type": "Integer"}, {"default": "True", "description":
          "Whether to delete the Experiment after it is finished", "name": "Delete
          Finished Experiment", "type": "Bool"}], "name": "Katib - Launch Experiment",
          "outputs": [{"description": "The hyperparameter set of the best Experiment
          Trial", "name": "Best Parameter Set", "type": "JsonObject"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "a93c64b052e810a0d0d0ada3f28a03b3e45e5a3e3bf03272d4bf6c67d5e14bac", "url":
          "https://raw.githubusercontent.com/kubeflow/pipelines/master/components/kubeflow/katib-launcher/component.yaml"}',
        pipelines.kubeflow.org/arguments.parameters: '{"Delete Finished Experiment":
          "False", "Experiment Name": "katib-example-{{ workflow.uid }}", "Experiment
          Namespace": "{{ workflow.namespace }}", "Experiment Spec": "{\"algorithm\":
          {\"algorithmName\": \"grid\"}, \"maxFailedTrialCount\": 3, \"maxTrialCount\":
          3, \"objective\": {\"goal\": 50, \"objectiveMetricName\": \"result\", \"type\":
          \"maximize\"}, \"parallelTrialCount\": 2, \"parameters\": [{\"feasibleSpace\":
          {\"max\": \"50\", \"min\": \"0\"}, \"name\": \"x\", \"parameterType\": \"int\"},
          {\"feasibleSpace\": {\"max\": \"50\", \"min\": \"0\"}, \"name\": \"y\",
          \"parameterType\": \"int\"}], \"trialTemplate\": {\"primaryContainerName\":
          \"real-my-container\", \"retain\": true, \"trialParameters\": [{\"description\":
          \"argument 1\", \"name\": \"X\", \"reference\": \"x\"}, {\"description\":
          \"argument 2\", \"name\": \"Y\", \"reference\": \"y\"}], \"trialSpec\":
          {\"apiVersion\": \"batch/v1\", \"kind\": \"Job\", \"spec\": {\"template\":
          {\"metadata\": {\"annotations\": {\"sidecar.istio.io/inject\": \"false\"}},
          \"spec\": {\"containers\": [{\"args\": [\"custom.py\", \"--x\", \"${trialParameters.X}\",
          \"--y\", \"${trialParameters.Y}\"], \"command\": [\"python\"], \"image\":
          \"129231402580.dkr.ecr.ap-northeast-1.amazonaws.com/base_image:katib-test\",
          \"name\": \"real-my-container\"}], \"restartPolicy\": \"Never\"}}}}}}",
          "Experiment Timeout Minutes": "60"}'}
  - name: launch-katib-experiment
    dag:
      tasks:
      - name: best-hp
        template: best-hp
        dependencies: [katib-launch-experiment]
        arguments:
          parameters:
          - {name: katib-launch-experiment-Best-Parameter-Set, value: '{{tasks.katib-launch-experiment.outputs.parameters.katib-launch-experiment-Best-Parameter-Set}}'}
      - {name: katib-launch-experiment, template: katib-launch-experiment}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
