version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - TZ=Asia/Seoul
      - API_ENV=local
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8080:8080
    expose:
      - 8080
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
