FROM python:3.9-slim

WORKDIR /fastapi/app
COPY Pipfile* /fastapi/app
RUN apt-get update
RUN pip install --upgrade pipenv
RUN pipenv install --dev --system --deploy

ENTRYPOINT [ "python", "main.py" ]
