version: '3'

services:
  app:
    build:
      context: docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
    expose:
      - 8000
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
